# Generated by Django 5.2.11 on 2026-05-09 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0012_alter_classification_options_alter_component_options_and_more",
        ),
        ("tcms_requirements", "0008_requirement_document_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="baselinerequirementsnapshot",
            name="payload",
            field=models.JSONField(
                default=dict, help_text="Full-fidelity field dump at snapshot time."
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the feature isn't scoped to a specific project.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirement_features",
                to="management.product",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfeature",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalfeature",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Set when the feature isn't scoped to a specific project.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="management.product",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="actual_end_date",
            field=models.DateField(
                blank=True, help_text="Populated when the programme closes.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short identifier unique within the product (e.g. 'PLAT26').",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="external_refs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Open-ended map for other ALM / PM tool IDs (Polarion, Azure DevOps, …).",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="jira_project_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="JIRA project key (e.g. 'PROJ') for cross-tool mapping.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Single accountable stakeholder.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Target or actual programme kickoff.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("active", "Active"),
                    ("on_hold", "On hold"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="active",
                help_text="Programme lifecycle state. Drives list filters and dashboard priority.",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="target_end_date",
            field=models.DateField(
                blank=True,
                help_text="Planned completion date; used in timeline KPIs.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="asil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("QM", "QM"),
                    ("A", "ASIL A"),
                    ("B", "ASIL B"),
                    ("C", "ASIL C"),
                    ("D", "ASIL D"),
                ],
                default="",
                help_text="Automotive Safety Integrity Level per ISO 26262. QM = quality managed (no safety impact); A → D is increasing safety risk, D being the most stringent (e.g. airbag deployment). Leave blank for non-automotive or non-safety requirements.",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="change_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required when status transitions to deprecated or superseded. Feeds ISO 9001 §10 corrective/preventive action evidence.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="dal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "DAL A (catastrophic)"),
                    ("B", "DAL B (hazardous)"),
                    ("C", "DAL C (major)"),
                    ("D", "DAL D (minor)"),
                    ("E", "DAL E (no effect)"),
                ],
                default="",
                help_text="Design Assurance Level per DO-178C (aviation software). A = catastrophic failure condition, E = no effect on safety. Leave blank for non-aviation software.",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="doc_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External controlled-document ID (e.g. 'QMS-SRS-042').",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="external_refs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Open-ended map for other ALM IDs (Polarion, DOORS, Jama, …).",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="identifier",
            field=models.CharField(
                db_index=True,
                help_text="Stable human ID (e.g. 'SYS-REQ-042'). Round-trips to external tools.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="iec62304_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Class A (no injury or damage to health possible)"),
                    ("B", "Class B (non-serious injury possible)"),
                    ("C", "Class C (death or serious injury possible)"),
                ],
                default="",
                help_text="Medical-device software safety class per IEC 62304. A = no injury possible, B = non-serious injury possible, C = death or serious injury possible. Leave blank for non-medical software.",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="jira_issue_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="JIRA issue key (e.g. 'PROJ-123'). Populated on push or round-trip import.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="parent_requirement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Parent in the decomposition tree (system → software → etc.).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tcms_requirements.requirement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="priority",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                db_index=True,
                default="medium",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="rationale",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why this requirement exists — ASPICE and ISO 9001 both value this.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="sil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "SIL 1"),
                    ("2", "SIL 2"),
                    ("3", "SIL 3"),
                    ("4", "SIL 4"),
                ],
                default="",
                help_text="Safety Integrity Level per IEC 61508 (industrial functional safety). 1 = lowest risk reduction, 4 = highest. Used for process-industry and machinery safety; leave blank otherwise.",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="source_section",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Section or page reference within the source doc (e.g. '§4.2.1').",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("implemented", "Implemented"),
                    ("verified", "Verified"),
                    ("deprecated", "Deprecated"),
                    ("superseded", "Superseded"),
                ],
                db_index=True,
                default="draft",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Set when status=superseded — points at the replacement requirement.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tcms_requirements.requirement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="verification_exemption_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required when verification_method=exempted.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirement",
            name="verification_method",
            field=models.CharField(
                choices=[
                    ("test", "Test"),
                    ("analysis", "Analysis"),
                    ("inspection", "Inspection"),
                    ("demonstration", "Demonstration"),
                    ("exempted", "Exempted (no verification required)"),
                ],
                default="test",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirementtestcaselink",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalrequirementtestcaselink",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("verifies", "Verifies"),
                    ("validates", "Validates"),
                    ("derives_from", "Derives from"),
                    ("related", "Related"),
                ],
                db_index=True,
                default="verifies",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequirementtestcaselink",
            name="suspect",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set true when the linked requirement is edited; cleared by reviewer.",
            ),
        ),
        migrations.AlterField(
            model_name="jiraintegrationconfig",
            name="custom_field_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Map our field names → JIRA custom_field IDs (e.g. 'level' → 'customfield_10011').",
            ),
        ),
        migrations.AlterField(
            model_name="jiraintegrationconfig",
            name="status_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Map plugin status → JIRA status, e.g. {"approved": "Done"}.',
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short identifier unique within the product (e.g. 'PLAT26').",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="change_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required when status transitions to deprecated or superseded. Feeds ISO 9001 §10 corrective/preventive action evidence.",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="doc_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External controlled-document ID (e.g. 'QMS-SRS-042').",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="external_refs",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Open-ended map for other ALM IDs (Polarion, DOORS, Jama, …).",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="identifier",
            field=models.CharField(
                db_index=True,
                help_text="Stable human ID (e.g. 'SYS-REQ-042'). Round-trips to external tools.",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="jira_issue_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="JIRA issue key (e.g. 'PROJ-123'). Populated on push or round-trip import.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="parent_requirement",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent in the decomposition tree (system → software → etc.).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_requirements",
                to="tcms_requirements.requirement",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="rationale",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why this requirement exists — ASPICE and ISO 9001 both value this.",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="source_section",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Section or page reference within the source doc (e.g. '§4.2.1').",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when status=superseded — points at the replacement requirement.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="tcms_requirements.requirement",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="verification_exemption_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required when verification_method=exempted.",
            ),
        ),
        migrations.AlterField(
            model_name="requirementcategory",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional hex colour for UI badges (e.g. #ec7a08).",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="requirementlevel",
            name="code",
            field=models.SlugField(
                help_text="Stable identifier (e.g. 'system', 'customer_requirement').",
                max_length=48,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="requirementlevel",
            name="order",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Rank; lower number = higher in the decomposition hierarchy. Used to sort level tiles and enforce parent/child ordering.",
            ),
        ),
        migrations.AlterField(
            model_name="requirementsource",
            name="reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL or path to the source document.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="requirementtestcaselink",
            name="suspect",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set true when the linked requirement is edited; cleared by reviewer.",
            ),
        ),
    ]
